"""Add Operation Table

Revision ID: b860a0d2f144
Revises: 036a2183baa6
Create Date: 2023-07-11 17:05:07.819766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b860a0d2f144'
down_revision = '036a2183baa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.String(length=255), nullable=False),
                    sa.Column('figi', sa.String(length=255), nullable=False),
                    sa.Column('instrument_type', sa.String(length=255), nullable=False),
                    sa.Column('date', sa.TIMESTAMP(), nullable=True),
                    sa.Column('operation_type', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    # ### end Alembic commands ###
